### ISSUE TITLE
Video Player sample /Navigating between controls 

### ISSUE THREAD

**Issue by ahmad-crossplatform** [Samsung/Tizen-CSharp-Samples#18]
Hello there , I just started to read about Tizen and the ability to do so with Xamarin . 
I just cannot find a sample of video player for the TV ,
I tried to clone  git://git.tizen.org/profile/tv/apps/dotnet/sample/videoplayer but it has no files. 

the other topic that might be answered if I have managed to clone that solutoin  is : do you have a recommended pattern to handle the events coming from the remote to navigate between different controls ?

**Comment by sgchoi5** [comment]
Hello,
We are trying to add more samples for Mobile/TV/Wearable.
In case of Video, you can refer to Player sample for mobile first from DEV branch.

Tizen C# Sample Page: https://developer.tizen.org/ko/development/sample/.net-application/tizen-samples
PlayerSample for Mobile: https://github.com/Samsung/Tizen-CSharp-Samples/tree/dev/Mobile/PlayerSample

The code of "dev" branch means it is not yet ready for public release. plz, consider that.

thanks
Ben

**Comment by rookiejava** [comment]
@ahmad-crossplatform  [This sample app](https://github.com/SamsungDForum/Xamarin.Media) is helpful to you.

**Comment by ahmad-crossplatform** [comment]
@sgchoi5  @rookiejava  thank you guys , how about handling the remote control directions ? Is there any best recommendation ?

**Comment by ahmad-crossplatform** [comment]
hello again , does any one have this but using CustomRenderes instead of implementing it as  service ?

**Comment by rookiejava** [comment]
1. In order to handle key events, you can use `ElmSharp.EcoreEvent` as below.

```cs
// Register key event callbacks for the window using the EcoreEvent.
EcoreEvent<EcoreKeyEventArgs> _keyUp = new EcoreEvent<EcoreKeyEventArgs>(EcoreEventType.KeyUp, EcoreKeyEventArgs.Create);

 _keyUp.On += (s, e) =>
{
 // write your code here using  e.Keyname and e.KeyCode
}
```
  _please refer to [KeyCode](http://developer.samsung.com/tv/tizen-net-tv/api-references/tizenfx-tv-api-references/Tizen.TV.Application.Window/KeyCode-Class). for more keycode details._

2. Video Player
You can make your own custom renderer for either VideoView or VideoPlayer refer to the sample app mentioned above. There is no big difference. And, we are preparing to contirubute a popoluar open source Xamarin.Forms media player  plugins for tizen such as [MediaManger](https://blog.xamarin.com/play-audio-and-video-with-the-mediamanager-plugin-for-xamarin/). You can use these plugins for your video player app when it available. (I'm not sure the date but we hope soonish.)

**Comment by hallower** [comment]
@ahmad-crossplatform 

Hi

This is not an answer for your question but I’d like to introduce TV video player sample and a lecture.
I think it’s quite helpful for making your own Video Player.

Xamarin Forms TV App Development for Tizen
http://tizenappschool.org/tutorial/71/contents/1

Sample code
https://s3-us-west-1.amazonaws.com/tizenschool/97/Lect3_Snapshot09_Add_PlayerButton_Final.zip

Actually the sample code is related with below lectures that is describe how to make a video player on Tizen TV in detail, but those are written as Korean language. I leave URLs of them for the information.

Cross Platform TV Application Development
http://tizenappschool.org/tutorial/95/contents/1
http://tizenappschool.org/tutorial/97/contents/1

**Comment by ahmad-crossplatform** [comment]
@hallower  thanks a lot , but for some reason I cannot see the media samples ... like the videos ... where do you get that from ?
