### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by nnarziev** [Samsung/Tizen-CSharp-Samples#91]
I imported the tizen sensors sample application into visual studio 2019. Using tizen package manager I installed certificate extension. Then, I created a new Samsung wearable certificate using tizen certificate manager. When I am trying to run the app on my connected wearable device, the visual studio keeps giving the following error: 
processing result : Check certificate error [-12] failed
Please, help me to solve this error!

**Comment by sgchoi5** [comment]
Contacting proper developer for your question.
How about to use Visual Studio 2017? It is more stable than 2019.

**Comment by winstone77** [comment]
This issue can be caused by various reasons. Thus, Could you check following points?
1. Check the active profile is right with certificate manager. 
2. Check following visual studio option 
  (Tools > Option > Tizen > Certification > Check the .TPK sign options.)
  --> Use profile of Tizen Certificate Manager should be selected and profile value should be correct.
3. Check the timeof Wearable device is correct.
